<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
final class Version20260105000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema for Reddit posts on PostgreSQL.';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();
        $this->abortIf(!($platform instanceof PostgreSQLPlatform), 'This migration is intended for PostgreSQL only.');

        $this->addSql(<<<'SQL'
CREATE TABLE reddit_post (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fullname VARCHAR(30) NOT NULL,
    title VARCHAR(512) NOT NULL,
    upvote_ratio INT NOT NULL,
    ups INT NOT NULL,
    created_at_utc TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    local_thumbnail VARCHAR(1024) DEFAULT NULL,
    local_mp4 VARCHAR(1024) DEFAULT NULL,
    CONSTRAINT PK_reddit_post PRIMARY KEY (id),
    CONSTRAINT UQ_reddit_fullname UNIQUE (fullname),
    CONSTRAINT UQ_reddit_title UNIQUE (title)
)
SQL);
}

    public function down(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();
        $this->abortIf(!($platform instanceof PostgreSQLPlatform), 'This migration is intended for PostgreSQL only.');

        $this->addSql('DROP TABLE IF EXISTS reddit_post');
    }
}
